import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ALGORITHM_VERSION, DEFAULT_PARAMETERS, type DepthImage, type Parameters, type PipelineResult } from "./algorithm/types";
import { decodeDepthImage } from "./algorithm/imageInput";
import { SYNTHETIC_EXAMPLES, getSynthetic } from "./algorithm/syntheticDepthMaps";
import { runPipeline } from "./algorithm/pipeline";
import { PARAMS, STAGES } from "./content";
import { downloadCanvas, imageDataToCanvas, renderStage, type StageKey } from "./visualization/canvasRendering";

type WorkerReply={id:number;result?:PipelineResult;error?:string};
// React 19's useRef typing requires an initializer; the worker is assigned on mount.
// @ts-expect-error intentional undefined initial worker reference
function usePipeline(image:DepthImage,parameters:Parameters,automatic:boolean,nonce:number){const[result,setResult]=useState<PipelineResult>();const[busy,setBusy]=useState(true);const[error,setError]=useState("");const id=useRef(0);const worker=useRef<Worker>();useEffect(()=>{try{worker.current=new Worker(new URL("./workers/pipeline.worker.ts",import.meta.url),{type:"module"});}catch{}return()=>worker.current?.terminate();},[]);useEffect(()=>{if(!automatic&&nonce===0)return;const timer=setTimeout(()=>{const request=++id.current;setBusy(true);setError("");const w=worker.current;if(w){w.onmessage=(e:MessageEvent<WorkerReply>)=>{if(e.data.id!==id.current)return;if(e.data.error)setError(e.data.error);else setResult(e.data.result);setBusy(false);};w.postMessage({id:request,image,parameters});}else{try{setResult(runPipeline(image,parameters));}catch(e){setError(e instanceof Error?e.message:String(e));}setBusy(false);}},120);return()=>clearTimeout(timer);},[image,parameters,automatic,nonce]);return{result,busy,error};}

function StageCanvas({result,stage,interactive=false,onHover}:{result:PipelineResult;stage:StageKey;interactive?:boolean;onHover?:(x:number,y:number)=>void}){const ref=useRef<HTMLCanvasElement>(null),[view,setView]=useState({zoom:1,x:0,y:0}),drag=useRef<{x:number;y:number;vx:number;vy:number}|null>(null);const pixels=useMemo(()=>renderStage(result,stage),[result,stage]);useEffect(()=>{const c=ref.current;if(!c)return;const ctx=c.getContext("2d")!,box=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=Math.max(1,box.width*dpr);c.height=Math.max(1,box.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,box.width,box.height);ctx.fillStyle="#0b0d0d";ctx.fillRect(0,0,box.width,box.height);const scale=Math.min(box.width/pixels.width,box.height/pixels.height)*view.zoom,dw=pixels.width*scale,dh=pixels.height*scale,dx=(box.width-dw)/2+view.x,dy=(box.height-dh)/2+view.y,tmp=document.createElement("canvas");imageDataToCanvas(pixels,tmp);ctx.imageSmoothingEnabled=view.zoom<2;ctx.drawImage(tmp,dx,dy,dw,dh);},[pixels,view]);const position=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!onHover)return;const b=e.currentTarget.getBoundingClientRect(),scale=Math.min(b.width/result.width,b.height/result.height)*view.zoom,dx=(b.width-result.width*scale)/2+view.x,dy=(b.height-result.height*scale)/2+view.y;onHover(Math.max(0,Math.min(result.width-1,Math.floor((e.clientX-b.left-dx)/scale))),Math.max(0,Math.min(result.height-1,Math.floor((e.clientY-b.top-dy)/scale))));};return <div className={interactive?"canvas-shell interactive":"canvas-shell"}><canvas ref={ref} onWheel={interactive?e=>{e.preventDefault();setView(v=>({...v,zoom:Math.max(.5,Math.min(16,v.zoom*(e.deltaY<0?1.15:.87)))}));}:undefined} onPointerDown={interactive?e=>{drag.current={x:e.clientX,y:e.clientY,vx:view.x,vy:view.y};e.currentTarget.setPointerCapture(e.pointerId);}:undefined} onPointerMove={interactive?e=>{position(e);if(drag.current)setView(v=>({...v,x:drag.current!.vx+e.clientX-drag.current!.x,y:drag.current!.vy+e.clientY-drag.current!.y}));}:undefined} onPointerUp={interactive?()=>drag.current=null:undefined}/>{interactive&&<div className="canvas-tools"><button onClick={()=>setView(v=>({...v,zoom:Math.min(16,v.zoom*1.5)}))}>+</button><button onClick={()=>setView(v=>({...v,zoom:Math.max(.5,v.zoom/1.5)}))}>−</button><button onClick={()=>setView({zoom:1,x:0,y:0})}>Fit</button><span>{Math.round(view.zoom*100)}%</span></div>}</div>}

const fmt=(n:number,d=3)=>Number.isFinite(n)?n.toFixed(d):"—";
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="toggle"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><i/></label>}
function saveText(name:string,text:string,type="application/json"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}

export function App(){const[image,setImage]=useState(()=>getSynthetic("cylinder"));const[synthetic,setSynthetic]=useState("cylinder");const[parameters,setParameters]=useState<Parameters>(DEFAULT_PARAMETERS);const[stage,setStage]=useState<StageKey>("finalRegions");const[advanced,setAdvanced]=useState(false),[automatic,setAutomatic]=useState(true),[nonce,setNonce]=useState(1),[hover,setHover]=useState({x:0,y:0}),[message,setMessage]=useState(""),[comparison,setComparison]=useState(50);const{result,busy,error}=usePipeline(image,parameters,automatic,nonce);const selected=STAGES.find(x=>x.key===stage)!;const update=useCallback((key:keyof Parameters,value:number|boolean)=>setParameters(p=>({...p,[key]:value})),[]);
  const loadSynthetic=(id:string)=>{setSynthetic(id);setImage(getSynthetic(id));setMessage("");};const upload=async(file?:File)=>{if(!file)return;try{const next=await decodeDepthImage(file,parameters.maximumDimension);setImage(next);setSynthetic("");setMessage(`Loaded ${file.name} locally. Nothing was uploaded.`);}catch(e){setMessage(e instanceof Error?e.message:String(e));}};
  const exportSettings=()=>saveText("hard-edge-settings.json",JSON.stringify({algorithmVersion:ALGORITHM_VERSION,input:{name:image.name,width:image.width,height:image.height},working:{width:image.width,height:image.height},parameters},null,2));const exportStats=(csv=false)=>{if(!result)return;if(csv){const head="id,area,diameter,perimeter,meanDepth,meanOutputDepth,meanDepthError,nx,ny,nz,slopeA,slopeB,kind,rmse,maxResidual,sourceRegions,scaleStatus";const rows=result.stats.map(s=>[s.id,s.area,s.diameter,s.perimeter,s.meanDepth,s.meanOutputDepth,s.meanDepthError,...s.meanNormal,...s.slope,s.kind,s.rmse,s.maxResidual,s.sourceRegions,s.scaleStatus].join(","));saveText("region-statistics.csv",[head,...rows].join("\n"),"text/csv");}else saveText("region-statistics.json",JSON.stringify(result.stats,null,2));};
  const p=hover.y*image.width+hover.x,inspect=result&&p<result.depth.length?{u:hover.x/Math.max(1,result.width-1),v:hover.y/Math.max(1,result.height-1),d:result.depth[p],n:[result.normals[p*3],result.normals[p*3+1],result.normals[p*3+2]],init:result.initialLabels[p],final:result.finalLabels[p],out:result.reconstruction[p],res:result.residual[p]}:null;
  return <div className="app"><header><div><span className="eyebrow">LOCAL GEOMETRY LAB · v{ALGORITHM_VERSION}</span><h1>Hard Edge</h1><p>Scale-constrained depth-map simplification</p></div><div className="metrics"><span><b>{image.width} × {image.height}</b>working image</span><span><b>{result?.audit.finalRegions??"—"}</b>final regions</span><span><b>{result?`${result.totalMs.toFixed(0)} ms`:"—"}</b>processing</span><button onClick={()=>setParameters(DEFAULT_PARAMETERS)}>Reset defaults</button></div></header>
    <aside><section className="hero-control"><div className="section-label">INPUT</div><label className="upload">Choose depth map<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files?.[0])}/><small>PNG · JPEG · WebP · processed locally</small></label><label className="select-label">Synthetic example<select value={synthetic} onChange={e=>loadSynthetic(e.target.value)}>{SYNTHETIC_EXAMPLES.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><p className="expectation">{SYNTHETIC_EXAMPLES.find(x=>x.id===synthetic)?.expectation||message}</p></section>
      <section><div className="section-label">CORE CONTROLS</div>{PARAMS.filter(x=>!x.advanced).map(def=><Parameter key={def.key} def={def} value={parameters[def.key] as number} defaultValue={DEFAULT_PARAMETERS[def.key] as number} onChange={v=>update(def.key,v)}/>)}</section>
      <section><button className="disclosure" onClick={()=>setAdvanced(v=>!v)}>{advanced?"−":"+"} Advanced controls</button>{advanced&&PARAMS.filter(x=>x.advanced).map(def=><Parameter key={def.key} def={def} value={parameters[def.key] as number} defaultValue={DEFAULT_PARAMETERS[def.key] as number} onChange={v=>update(def.key,v)}/>)}</section>
      <section className="toggles"><Toggle label="White is near" checked={parameters.whiteIsNear} onChange={v=>update("whiteIsNear",v)}/><Toggle label="Automatic recomputation" checked={automatic} onChange={setAutomatic}/><Toggle label="Bounded reconstruction" checked={parameters.boundedReconstruction} onChange={v=>update("boundedReconstruction",v)}/>{!automatic&&<button className="primary" onClick={()=>setNonce(n=>n+1)}>Recompute now</button>}</section>
      <section><div className="section-label">EXPORTS</div><div className="export-grid"><button disabled={!result} onClick={()=>result&&downloadCanvas(renderStage(result,"reconstruction"),"reconstructed-depth.png")}>Depth PNG</button><button disabled={!result} onClick={()=>result&&downloadCanvas(renderStage(result,"overlay"),"hard-edge-mask.png")}>Edge PNG</button><button disabled={!result} onClick={()=>result&&downloadCanvas(renderStage(result,"finalRegions"),"partitions.png")}>Regions PNG</button><button onClick={exportSettings}>Settings JSON</button><button disabled={!result} onClick={()=>exportStats()}>Stats JSON</button><button disabled={!result} onClick={()=>exportStats(true)}>Stats CSV</button></div></section>
    </aside>
    <main>{error&&<div className="error">{error}</div>}{message&&<div className="notice">{message}</div>}<nav className="stage-nav">{STAGES.map(s=><button className={stage===s.key?"active":""} onClick={()=>setStage(s.key)} key={s.key}>{s.title}</button>)}</nav>
      <div className="workbench"><div className="viewer"><div className="viewer-head"><div><span className="eyebrow">SELECTED STAGE</span><h2>{selected.title}</h2></div>{busy&&<span className="processing">Processing…</span>}</div>{result?<StageCanvas result={result} stage={stage} interactive onHover={(x,y)=>setHover({x,y})}/>:<div className="loading">Preparing typed-array pipeline…</div>}<div className="legend"><span><i className="raw"/>raw candidate</span><span><i className="kept"/>retained</span><span><i className="removed"/>scale removed</span></div></div>
        <div className="inspector"><span className="eyebrow">PIXEL INSPECTOR</span><h3>x {hover.x} · y {hover.y}</h3>{inspect?<dl><dt>u / v</dt><dd>{fmt(inspect.u)} / {fmt(inspect.v)}</dd><dt>Input depth</dt><dd>{fmt(inspect.d,4)}</dd><dt>Normal</dt><dd>[{inspect.n.map(v=>fmt(v,2)).join(", ")}]</dd><dt>Initial / final region</dt><dd>{inspect.init} / {inspect.final}</dd><dt>Output depth</dt><dd>{fmt(inspect.out,4)}</dd><dt>Residual</dt><dd>{fmt(inspect.res,4)}</dd></dl>:<p>Hover the canvas.</p>}<p className="privacy">Your image stays in this tab. The worker receives pixels only in browser memory.</p></div>
      </div>
      <section className="explanation"><div><span className="eyebrow">WHAT THIS STEP SHOWS</span><p>{selected.shows}</p></div><div><span className="eyebrow">HOW IT IS CALCULATED</span><p>{selected.calculation}</p><code>{selected.formula}</code></div><div><span className="eyebrow">WHY IT IS NECESSARY</span><p>{selected.why}</p></div><div><span className="eyebrow">WHAT CAN GO WRONG</span><p>{selected.risk}</p><small>Affected by: {selected.params.join(", ")||"diagnostic only"}</small></div></section>
      {result&&<><section className="comparison"><div className="section-title"><span className="eyebrow">20 · INPUT / OUTPUT COMPARISON</span><h2>Drag to compare retained structure</h2></div><div className="wipe"><StageCanvas result={result} stage="input"/><div className="wipe-output" style={{clipPath:`inset(0 0 0 ${comparison}%)`}}><StageCanvas result={result} stage="reconstruction"/></div><i style={{left:`${comparison}%`}}/><input aria-label="Input output comparison" type="range" min="0" max="100" value={comparison} onChange={e=>setComparison(+e.target.value)}/></div><p>Residual is diagnostic only. It never creates a boundary, never triggers another plane, and is never added back.</p></section>
      <section className="thumb-section"><div className="section-title"><span className="eyebrow">PIPELINE AT A GLANCE</span><h2>Every decision remains observable</h2></div><div className="thumb-grid">{STAGES.map(s=><button key={s.key} onClick={()=>setStage(s.key)} className={stage===s.key?"active":""}><StageCanvas result={result} stage={s.key}/><span>{s.title}</span></button>)}</div></section>
      <ScaleAudit result={result}/><RegionTable result={result}/></>}
      <Overview/></main></div>}

function Parameter({def,value,defaultValue,onChange}:{def:(typeof PARAMS)[number];value:number;defaultValue:number;onChange:(v:number)=>void}){return <details className={def.key==="minimumScale"?"parameter primary-param":"parameter"}><summary><div><label>{def.name} {def.symbol&&<em>{def.symbol}</em>}</label><small>Default {defaultValue} {def.unit}</small></div><div className="range-row"><input aria-label={def.name} type="range" min={def.min} max={def.max} step={def.step} value={value} onChange={e=>onChange(+e.target.value)}/><input aria-label={`${def.name} numeric value`} type="number" min={def.min} max={def.max} step={def.step} value={value} onChange={e=>onChange(Math.max(def.min,Math.min(def.max,+e.target.value)))}/><span>{def.unit}</span></div></summary><div className="param-info"><p>{def.meaning}</p><code>{def.formula}</code><dl><dt>Increase</dt><dd>{def.up}</dd><dt>Decrease</dt><dd>{def.down}</dd><dt>Too low</dt><dd>{def.low}</dd><dt>Too high</dt><dd>{def.high}</dd><dt>Scale interaction</dt><dd>{def.scale}</dd></dl></div></details>}
function ScaleAudit({result}:{result:PipelineResult}){const a=result.audit;const cards:[[string,string|number],...Array<[string,string|number]>]=[["Current s",`${a.minimumScale}px`],["Minimum edge",fmt(a.minimumEdgeLength,1)],["Minimum diameter",fmt(a.minimumRegionDiameter,1)],["Minimum area",fmt(a.minimumRegionArea,0)],["Raw edge components",a.rawComponents],["Temporary micro-regions",a.microRegions],["Posterization joins",a.agglomerationMerges],["Posterization passes",a.agglomerationPasses],["Short components removed",a.removedShortComponents],["Unsupported links removed",a.removedUnsupportedLinks],["Structural regions",a.provisionalRegions],["Below-scale regions",a.belowScaleRegions],["Scale merge operations",a.mergeOperations],["Final regions",a.finalRegions],["Scale iterations",a.iterations]];return <section className="audit"><div className="section-title"><span className="eyebrow">SCALE AUDIT</span><h2>{a.finalViolations?`${a.finalViolations} unresolved invariant warning(s)`:"All reported scale invariants explained"}</h2><p>A retained boundary must be supported by concentrated hard evidence across a region interface and have sufficient spatial support on both sides at the selected scale. Temporary posterization regions are always joined unless that evidence survives; regions below the diameter or area thresholds are then merged.</p></div><div className="audit-grid">{cards.map(([k,v])=><div key={k}><b>{v}</b><span>{k}</span></div>)}</div><div className={a.converged?"status good":"status warn"}>{a.converged?"Converged before the safe iteration limits":"Stopped at a safe iteration limit"}</div></section>}
function RegionTable({result}:{result:PipelineResult}){return <section className="regions"><div className="section-title"><span className="eyebrow">REGION STATISTICS</span><h2>One row · one plane</h2></div><div className="table-wrap"><table><thead><tr><th>ID</th><th>Area</th><th>Diameter</th><th>Perimeter</th><th>Mean in</th><th>Mean out</th><th>Mean error</th><th>Mean normal</th><th>Slope</th><th>Surface</th><th>RMSE</th><th>Merges</th><th>Scale</th></tr></thead><tbody>{result.stats.map(s=><tr key={s.id} className={s.scaleStatus==="violation"?"violation":""}><td><b>{s.id}</b></td><td>{s.area}</td><td>{fmt(s.diameter,1)}</td><td>{fmt(s.perimeter,0)}</td><td>{fmt(s.meanDepth,4)}</td><td>{fmt(s.meanOutputDepth,4)}</td><td>{fmt(s.meanDepthError,6)}</td><td>[{s.meanNormal.map(v=>fmt(v,2)).join(", ")}]</td><td>[{s.slope.map(v=>fmt(v,2)).join(", ")}]</td><td>{s.kind}{s.slopeClamped?" · clamped":""}</td><td>{fmt(s.rmse,4)}</td><td>{s.sourceRegions}</td><td>{s.scaleStatus}</td></tr>)}</tbody></table></div></section>}
function Overview(){const terms=["Depth map — a scalar distance-like value per pixel.","Surface normal — the local facing direction inferred from depth derivatives.","Hard depth discontinuity — an abrupt depth step such as a silhouette or occlusion.","Hard normal discontinuity — an abrupt facing change such as a sharp crease.","Rounded transition — geometric change distributed over several links.","Edge concentration — the fraction of nearby variation in a narrow central band.","Micro-region — a temporary deterministic watershed cell that is never an output surface by itself.","Partition — a four-connected set of pixels not separated by retained barriers.","Spatial support — how much scale-sized neighborhood each boundary side occupies.","Minimum spatial scale — the smallest independent feature diameter/support in working pixels.","Characteristic diameter — twice the maximum grid distance to a region boundary.","Mean-preserving plane — one centered plane whose average equals the region’s input average.","Residual — discarded input minus reconstruction; diagnostic only."];return <section className="overview"><div className="section-title"><span className="eyebrow">ALGORITHM OVERVIEW</span><h2>Continuity proposes regions. Hardness and scale decide which survive.</h2></div><div className="overview-grid"><article><h3>Why fragmented edges can still partition</h3><p>Deterministic seeds grow into temporary micro-regions along low-cost paths. Adjacent regions are then joined using all evidence along their shared interface, so a boundary does not depend on a perfectly closed chain of edge pixels.</p><h3>Why curves stay whole</h3><p>A cylinder has many normals, but their changes are distributed. Its temporary regions therefore join, and its symmetric average normal becomes nearly camera-facing.</p><h3>Why corners remain</h3><p>A sharp corner concentrates a normal change into a narrow band. Aggregate interface evidence plus scale-sized support keeps it as an unsoftened boundary.</p></article><article><h3>No residual-driven faceting</h3><p>Temporary regions are not plane-fit facets. High plane error is never permission to split: every final partition gets exactly one plane, and residual is measured only afterward and discarded.</p><h3>Why tiny windows disappear</h3><p>A small sharp window can be detected and initially influence an interface, then fail length, side-support, diameter, or area at scale s and merge into its best adjacent region.</p></article></div><details><summary>Glossary</summary><ul>{terms.map(t=><li key={t}>{t}</li>)}</ul></details></section>}
