import type { Parameters } from "./algorithm/types";
import type { StageKey } from "./visualization/canvasRendering";

export type ParamDef={key:keyof Parameters;name:string;symbol?:string;unit:string;min:number;max:number;step:number;advanced?:boolean;meaning:string;formula:string;up:string;down:string;low:string;high:string;scale:string};
const P=(key:keyof Parameters,name:string,unit:string,min:number,max:number,step:number,meaning:string,formula:string,up:string,down:string,low:string,high:string,advanced=false,symbol?:string):ParamDef=>({key,name,unit,min,max,step,meaning,formula,up,down,low,high,advanced,symbol,scale:key==="minimumScale"?"This is the scale itself.":"This control is independent of s, but changes what reaches or survives the scale test."});
export const PARAMS:ParamDef[]=[
P("minimumScale","Minimum spatial scale","px",1,96,1,"Smallest independently represented feature support.","s; length≥λL·s, diameter≥λD·s, area≥λA·s²","Removes larger details and thin features.","Allows finer hard geometry.","Noise and tiny details survive.","Meaningful features merge away.",false,"s"),
P("depthGeometryScale","Depth geometry scale","×",.1,10,.1,"Maps depth derivatives to normal tilt.","n=normalize(−k gx,−k gy,1)","Normals tilt more for the same gradient.","Normals face the camera more.","Creases weaken.","Noise can create extreme tilt.",false,"k"),
P("smoothingSigma","Normal smoothing sigma","px",0,5,.1,"Blur used only for derivatives and normals.","dσ=Gσ*d","Suppresses noisy normals and broadens creases.","Preserves narrow changes.","Normal noise creates edges.","Sharp creases wash out."),
P("depthJumpThreshold","Depth jump threshold","depth",.001,.25,.001,"Adjacent depth change that has unit strength.","Cd=|dq−dp|/τd","Requires stronger silhouettes.","Detects smaller depth jumps.","Noise becomes a candidate edge.","Real silhouettes can disappear.",false,"τd"),
P("normalJumpThresholdDeg","Normal jump threshold","°",1,90,1,"Adjacent normal-angle change with unit strength.","Cn=acos(n·n′)/τn","Keeps only sharper creases.","Detects gentler turns.","Tight curvature may look hard.","Sharp corners may be missed.",false,"τn"),
P("hardnessWindow","Hardness window half-width","px",2,20,1,"Neighborhood used to judge concentrated versus distributed change.","T=Σ C over ±h","Rejects broader rounded transitions.","Makes hardness more local.","Rounded transitions can split.","Nearby edges can suppress each other.",false,"h"),
P("centralBand","Central edge-band half-width","px",0,4,1,"Narrow band allowed to hold a hard discontinuity.","B=Σ C over ±b, b<h","Allows antialiased or broadened edges.","Requires near one-pixel sharpness.","Antialiased edges can vanish.","Rounded turns can pass.",false,"b"),
P("minimumConcentration","Minimum concentration","ratio",.05,.95,.01,"Minimum nearby variation inside the central band.","Q=B/(T+ε)≥Qmin","Keeps only abrupt transitions.","Allows gradual transitions.","Curves may be partitioned.","Real broadened edges may vanish.",false,"Qmin"),
P("flatnessAngleDeg","Flatness angle threshold","°",0,20,.25,"Average normals closer than this become exactly flat.","acos(n̄z)<threshold ⇒ a=b=0","Makes more regions constant-depth.","Keeps shallow gradients.","Tiny meaningless gradients remain.","Useful tilt gets flattened."),
P("concentrationExponent","Concentration exponent","γ",.5,4,.1,"Shapes the displayed hard-edge score only.","H=max(Ccentral)·Q^γ","Visually penalizes diffuse changes.","Shows softer candidate responses.","Display overemphasizes diffuse edges.","Display hides moderate edges.",true,"γ"),
P("minimumBoundaryLengthFactor","Minimum boundary-length factor","×s",0,4,.1,"Minimum connected edge-chain length.","length≥λL·s","Removes longer scratches.","Keeps shorter fragments.","Tiny edge fragments survive.","Short real creases vanish.",true,"λL"),
P("minimumSideSupportFraction","Minimum side-support fraction","ratio",.05,.45,.01,"Required sampled neighborhood fraction on each side.","min(supportA,supportB)≥fraction","Rejects thinner or one-sided features.","Allows narrower features.","Tiny details survive.","Narrow valid features disappear.",true),
P("minimumDiameterFactor","Minimum diameter factor","×s",.5,2,.05,"Minimum characteristic diameter for a region.","2·max interior distance≥λD·s","Merges wider regions.","Allows narrower regions.","Slivers survive.","Legitimate regions merge.",true,"λD"),
P("minimumAreaFactor","Minimum area factor","×s²",0,2,.05,"Minimum region area.","area≥λA·s²","Merges larger compact details.","Allows smaller regions.","Specks survive.","Compact features merge too soon.",true,"λA"),
P("mergeNormalWeight","Merge normal weight","weight",0,5,.1,"Normal similarity when selecting a merge destination.","cost+=wn·angle(n̄A,n̄B)","Favors similarly oriented neighbors.","Lets depth and shared length dominate.","Merges may cross a crease.","Depth-disparate surfaces may merge.",true),
P("mergeDepthWeight","Merge depth weight","weight",0,5,.1,"Mean-depth similarity when selecting a merge destination.","cost+=wd·|d̄A−d̄B|","Favors similar-depth neighbors.","Lets normals and boundary length dominate.","Merges may jump depth.","Orientation can be ignored.",true),
P("maximumPlaneSlope","Maximum plane slope","depth/u-v",.1,20,.1,"Numerical limit on reconstructed slope magnitude.","||(a,b)||≤maximum","Allows steeper output planes.","Clamps more gradients.","Tilted planes flatten.","Near-grazing normals become unstable.",true),
P("maximumDimension","Maximum working dimension","px",128,1536,32,"Largest processed image side after local downsampling.","scale=min(1,maxDim/max(w,h))","Preserves more detail at higher cost.","Processes faster with less detail.","Rounded changes may quantize as sharp.","Memory and latency grow.",true),
P("boundaryOpacity","Boundary overlay opacity","ratio",0,1,.05,"Opacity of retained-edge overlays.","visualization only","Makes boundaries more prominent.","Reveals more of the depth image.","Boundaries are hard to see.","The source is obscured.",true),
];

export type StageDef={key:StageKey;title:string;shows:string;calculation:string;why:string;risk:string;formula:string;params:string[]};
export const STAGES:StageDef[]=[
{key:"input",title:"01 · Input depth",shows:"Normalized valid depth pixels.",calculation:"RGB is converted to luminance; transparent pixels are invalid.",why:"This is the untouched depth used for means and reconstruction diagnostics.",risk:"Incorrect near/far polarity reverses the geometry.",formula:"d=0.2126R+0.7152G+0.0722B",params:["White is near"]},
{key:"smoothed",title:"02 · Derivative smoothing",shows:"The copy used only for derivative estimation.",calculation:"A separable Gaussian blur ignores invalid pixels.",why:"It stabilizes normals without altering preserved mean depth.",risk:"Too much blur broadens sharp creases.",formula:"dσ=Gσ*d",params:["Normal smoothing sigma"]},
{key:"normals",title:"03 · Estimated normals",shows:"Full image-space unit normals encoded as RGB.",calculation:"Central/one-sided derivatives in normalized coordinates form an orthographic normal.",why:"Normal jumps expose sharp creases even when depth is continuous.",risk:"Noise or very low resolution can make smooth geometry look sharp.",formula:"n=normalize(−k gx,−k gy,1)",params:["Depth geometry scale","Normal smoothing sigma"]},
{key:"depthChanges",title:"04 · Depth-link strength",shows:"Normalized adjacent depth changes.",calculation:"Horizontal and vertical links are measured independently.",why:"Silhouettes and occlusions can block connectivity.",risk:"A low threshold reacts to noise.",formula:"Cd=|dq−dp|/τd",params:["Depth jump threshold"]},
{key:"normalChanges",title:"05 · Normal-link strength",shows:"Adjacent normal-angle changes.",calculation:"The clamped dot product is converted to an angle.",why:"Sharp corners can exist without a depth step.",risk:"Thresholding this alone would facet curvature.",formula:"Cn=acos(clamp(n·n′))/τn",params:["Normal jump threshold"]},
{key:"combined",title:"06 · Combined local change",shows:"The stronger depth or normal response per link.",calculation:"The maximum preserves either type of hard evidence.",why:"A silhouette or crease can independently propose a boundary.",risk:"C alone cannot distinguish curves from corners.",formula:"C=max(Cd,Cn)",params:["Depth jump threshold","Normal jump threshold"]},
{key:"concentration",title:"07 · Edge concentration",shows:"How much nearby change lies in the narrow center band.",calculation:"Central variation is divided by variation in a wider scan-line window.",why:"Distributed curvature stays connected even though its normals vary.",risk:"A window that is too narrow can mistake rounded turns for hard edges.",formula:"Q=B/(T+ε)",params:["Hardness window","Central edge-band","Minimum concentration"]},
{key:"rawEdges",title:"08 · Raw hard edges",shows:"Concentrated candidates after non-maximum suppression.",calculation:"A link needs central strength ≥1 and Q≥Qmin.",why:"These are the only links eligible to become boundaries.",risk:"They may still be too short or lack spatial support.",formula:"maxCentral≥1 ∧ Q≥Qmin",params:["Minimum concentration"]},
{key:"removedEdges",title:"09 · Scale-removed edges",shows:"Short edges in coral and unsupported edges in violet.",calculation:"Connected length and fixed 9×9 two-sided sampling remove links.",why:"Sharpness alone does not make a tiny feature representable.",risk:"Overly strict support can remove narrow but intended features.",formula:"length≥λL·s; supportA,B≥f",params:["Minimum spatial scale","Boundary-length factor","Side support"]},
{key:"initialRegions",title:"10 · Initial partitions",shows:"Four-connected regions before scale enforcement.",calculation:"Flood fill crosses every valid unblocked link.",why:"It exposes what raw hard evidence would preserve.",risk:"Tiny regions are expected at this stage.",formula:"connected components of unblocked pixel graph",params:[]},
{key:"support",title:"11 · Local scale support",shows:"Smaller of the two sampled side fractions.",calculation:"A deterministic 9×9 grid is scaled around each boundary midpoint.",why:"Runtime stays constant per tested link as s grows.",risk:"Very irregular sides may be under-sampled.",formula:"support=min(countA,countB)/validSamples",params:["Minimum spatial scale","Side support"]},
{key:"belowScale",title:"12 · Below-scale regions",shows:"Regions failing diameter or area in coral.",calculation:"A grid distance transform estimates the maximum interior radius.",why:"Independent regions must have enough spatial support.",risk:"Thin meaningful objects can deliberately disappear.",formula:"diameter<λD·s or area<λA·s²",params:["Minimum spatial scale","Diameter factor","Area factor"]},
{key:"merges",title:"13 · Region merges",shows:"Below-scale pixels colored by proposed destination.",calculation:"Destination cost uses normal difference, depth difference, and shared boundary.",why:"Geometry chooses where a rejected region goes, not whether it survives.",risk:"Extreme weights can choose a visually surprising neighbor.",formula:"wn·angle+wd·Δdepth−shared/perimeter",params:["Merge normal weight","Merge depth weight"]},
{key:"finalRegions",title:"14 · Final partitions",shows:"Deterministic colors for final connected regions.",calculation:"Labels are compacted after support pruning and scale merges.",why:"Each color receives exactly one output plane.",risk:"Four-connectivity is stair-stepped at high zoom.",formula:"final connected components",params:["Minimum spatial scale"]},
{key:"overlay",title:"15 · Final boundaries",shows:"Retained hard boundaries over the original depth.",calculation:"Adjacent final labels draw an unsoftened boundary.",why:"It verifies that only surviving discontinuities partition the image.",risk:"High overlay opacity can obscure source detail.",formula:"label(p)≠label(q)",params:["Boundary overlay opacity"]},
{key:"averageNormals",title:"16 · Region mean normals",shows:"One uniform normal color per final partition.",calculation:"Unit normals are summed and renormalized with equal weights.",why:"A symmetric cylinder averages to a camera-facing normal and remains one cutout.",risk:"Near-zero averages fall back to camera-facing.",formula:"n̄=normalize(Σn)",params:["Flatness angle threshold"]},
{key:"reconstruction",title:"17 · One-plane reconstruction",shows:"Exactly one flat or gradient depth surface per region.",calculation:"Slope comes from the mean normal; a bounded intercept bisection preserves mean depth.",why:"No plane-fitting residual is allowed to split a region.",risk:"Clipping changes slope shape near bounds, while mean is retained.",formula:"d̂=d̄+a(u−ū)+b(v−v̄)",params:["Flatness angle threshold","Maximum plane slope"]},
{key:"residual",title:"18 · Signed residual",shows:"Input minus reconstruction, centered at zero.",calculation:"Calculated after segmentation and never fed back.",why:"It explains discarded curvature and detail without restoring them.",risk:"Treating residual as edge evidence would violate the algorithm.",formula:"r=d−d̂",params:[]},
{key:"absResidual",title:"19 · Absolute residual",shows:"Magnitude of discarded depth variation.",calculation:"Absolute value of the signed diagnostic.",why:"It summarizes approximation cost without authorizing new partitions.",risk:"A large value is not permission to split.",formula:"|r|=|d−d̂|",params:[]},
];
